### ISSUE TITLE
Jammy B18 xfce fails to boot

### ISSUE THREAD

**Issue by Simzie** [radxa-build/rock-5a#2]
Fails to start Light Display Manager
Fails to start dnsmasq
Locked in "A start job is running for Hold until boot process finishes up (15min 53s / no limit)"

Have installed on sd card, attempted multiple times (with and without changes to before.txt). Will also try alternatives such as the CLI version soon. Would certainly be nice to have a working version of Ubuntu considering the NPU toolkit appears to demand it.

**Comment by RadxaYuntian** [comment]
We do not officially support Ubuntu, and in current state desktop is unlikely to work due to missing hardware enablement packages (which is why we don't support it). The only reason we produce it is because ROS requires it.

I do want to know why you think NPU requires Ubuntu. I don't recall such limitation. Can you link it?

**Comment by Simzie** [comment]
Yes I've used the NPU with the RKNPU2 example with debian but it is not particularly user friendly. I was wanting to use the rknn-toolkit2 with python, which states on the github page "Currently only support on Ubuntu 18.04 python 3.6 / Ubuntu 20.04 python 3.8 / Ubuntu 22.04 python 3.10". (https://github.com/rockchip-linux/rknn-toolkit2/tree/master).

When attempting to pip install the whl package on debian it states: ERROR: rknn_toolkit2-1.5.2+b642f30c-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform, however I haven't tried installing python 3.10 or 3.8 to use it.

**Comment by Simzie** [comment]
Ok, so I think you can only use the toolkit lite version on the device, and those other packages must just be for connected pc, however you have to take a dive through the lite docs to find this out (down several directories), or be savvy enough with your x86 vs aarch64 knowledge, which clearly I wasn't. Rockchip could really work on providing more information in their readme as if you overlook going through the lite docs you'd never know better.  Anyway, my bad and yes you don't need Ubuntu.

Alright, from here on out I will treat all Ubuntu versions put out be Radxa as simply junk (you seem to consider them to be), and just stick to the debian versions.
