### ISSUE TITLE
Add Raspberry Pi 7 inch touch screen overlay to ROCK 5a rsetup

### ISSUE THREAD

**Issue by milnepe** [radxa-build/rock-5a#5]
An overlay exists for the Raspberry Pi 7" display on the ROCK 5a [rock-5a-raspi-7inch-touchscreen.dts](https://github.com/radxa/overlays/blob/main/arch/arm64/boot/dts/rockchip/overlays/rock-5a-raspi-7inch-touchscreen.dts) but it is not available in rsetup.

Please add to the latest image.

**Comment by RadxaYuntian** [comment]
Please upgrade your system. We just released a new kernel, which include this overlay.

**Comment by milnepe** [comment]
I am on Debian Bullseye KDE Build 18 which is the latest. As you can see below the dtbo is missing:

radxa@rock-5a:~$ uname -r
5.10.110-12-rockchip

radxa@rock-5a:~$ ls /boot/dtbo/rock-5*
/boot/dtbo/rock-5a-radxa-camera-4k.dtbo.disabled
/boot/dtbo/rock-5a-radxa-display-10fhd.dtbo.disabled
/boot/dtbo/rock-5a-radxa-display-10hd.dtbo.disabled
/boot/dtbo/rock-5a-radxa-display-8hd.dtbo.disabled
/boot/dtbo/rock-5a-rpi-camera-v2.dtbo.disabled
/boot/dtbo/rock-5a-sata.dtbo.disabled
/boot/dtbo/rock-5a-spi-flash.dtbo.disabled
/boot/dtbo/rock-5b-hdmi1-8k.dtbo.disabled
/boot/dtbo/rock-5b-hdmi2-8k.dtbo.disabled
/boot/dtbo/rock-5b-radxa-camera-4k.dtbo.disabled
/boot/dtbo/rock-5b-radxa-display-10fhd.dtbo.disabled
/boot/dtbo/rock-5b-radxa-display-10hd.dtbo.disabled
/boot/dtbo/rock-5b-radxa-display-8hd.dtbo.disabled
/boot/dtbo/rock-5b-raspi-7inch-touchscreen.dtbo.disabled
/boot/dtbo/rock-5b-rpi-camera-v2.dtbo.disabled
/boot/dtbo/rock-5b-sata.dtbo.disabled

**Comment by RadxaYuntian** [comment]
Except we have published a newer kernel (5.10.110-21) on our apt repo: https://github.com/radxa-repo/bullseye/blob/gh-pages/.pool/linux-image-5.10.110-21-rockchip_5.10.110-21-d4b5d0d1d_arm64.deb

You could use `rsetup` to perform `System Update`:https://docs.radxa.com/en/radxa-os/rsetup#system-maintenance

**Comment by milnepe** [comment]
The update has pulled in the latest kernel so the overlay is there now, thanks for your help!
