### ISSUE TITLE
The GPU drivers support

### ISSUE THREAD

**Issue by augetyz** [radxa-build/rock-5a#6]

**Comment by augetyz** [comment]
Which img support the gpu drivers ,I use these img from build18 and most of them can’t use gpu

**Comment by RadxaYuntian** [comment]
All desktop images support GPU. The catch is that the GPU driver used in those systems (Arm Mali) does not support OpenGL, which is what most of desktop applications use. It mainly supports OpenGL ES which is what Android apps use.

We will support OpenGL in Debian 12 image with open source panthor GPU driver.
